spring:
  h2:
    console:
      enabled: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/devMigrations
jwt:
  secret: '3fan9K8CMyXX96UAL6Dd6VRyXmRp5ExApNTw6H6keJ6ss9SDC8cGJQhDL8X6jf5uFm6vDKKn4CgFTxHL3xaScw5KckgExGrYcUgRhB2rKAkx2P7tMCUqscq3p9V68nuSsNDSnCUPAYpGEYN3Qkf6Bf4fW6b7wpBjKTMNQSJuc8cFuwy2yhpdbvUCWUNeSZzpxBTdSHhNJKHAbVjqAzMskbXQFSVrqfe2HJtwHCCSQzAJKymQ9hgtBRwJTmVzjC86gzGTSutDc3XMLsP2r3Fxmb2WpKTRa659DnU7fUbBsWmdGpK3YrFBQnzVtQrmuRqQBa6X3SJbYaNRNCbJ2jkgmjFTd49ufMqY4etFbp9sEuURwHp9ktsKcbtmwcrZhkwqDFue2Jprf2PDA3ANAP4yHGSuB7MdUWCk2z7TfraxTmHFgTdkdzhYGTCBpJeQum7MDnVw3fqDp2xepqSEA8sH6PhT3JpHPrRWuS7agajR3teeTnxFv3vjvgQdyE9ebu7U4qh66Q3fwYT5yGAffdbsyyazRGjccKtQMKGsh24twgScHs6myP5tBKyVTnmwTnscKXVBMW7rDtzkUVPy32p7JD2zmpNwec9j7XmqseGp489H4Kwr2X9QDqPCycSyrMu9wPxNu5bhyNcN35VQr6fjZkbYRjsyE4aT3tbGjaSRkw6zmwxd3dAqx8u6RRFU7LJX4C5VWaRvxkMHB4QBbmLSwZYHHaubTuZSY9PtptmZNEYd5ksJdvuq4wQXPR5yr2ExXKpWw46FdL8kB2TMdDwj6dr9dNvE8Yqjg8CVAZtEH87CR35bMD3m4PK362tJ3UDvF8h6uCmDbs4XLVAZm6TcR2aTAn2v3jLB9DZuStWkTbq5nHqM8W97eYxMYgcZx5pSpEfA5kLAh7a73j5kBk9EUtpg5MjyDNvESN6yd6cUPnMzvtCFaK62Xb2asrDfbUJhwzmebgHYEUgSjYQmUTBgUykAJG6JB8EDKBB6fa2PTHxfzJRHPQCCxNdj8vEEwygG'
hall:
  image: /hall.png
  imageBaseWidth: 1000
