jwt:
  secret: ${JWT_SECRET_KEY}
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATA_STORE_CONNECTION_STRING}
    driverClassName: ${DATA_STORE_DRIVER}
    username: ${DATA_STORE_USERNAME}
    password: ${DATA_STORE_PASSWORD}
  flyway:
    url: ${DATA_STORE_CONNECTION_STRING}
    user: ${DATA_STORE_FLYWAY_USERNAME}
    password: ${DATA_STORE_FLYWAY_PASSWORD}


