spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/app_database'
    driverClassName: org.mariadb.jdbc.Driver
    username: 'root'
    password: 'admin'
  flyway:
    url: 'jdbc:mariadb://localhost:3306/app_database'
    user: root
    password: admin