spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: 'root'
    password: 'admin'
  flyway:
    url: 'jdbc:h2:mem:testdb;mode=mysql'
    user: root
    password: admin