apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rc_all.fullname" . }}
  labels:
    {{- include "rc_all.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rc_all.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rc_all.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rc_all.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: DATA_STORE_DRIVER
              value: "{{ .Values.rc_all.dataSource.driver }}"
            - name: SPRING_CONFIG_LOCATION
              value: "/config/config.yml"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ include "rc_all.fullname" . }}.jwt.secret"
                  key: "jwtKey"
          volumeMounts:
            - name: application-config
              mountPath: "/config"
              readOnly: true
          envFrom:
            - prefix: "DATA_STORE"
              secretRef:
                name: "{{ include "rc_all.fullname" . }}.data.store.secret"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: application-config
          configMap:
            name: "{{ .Values.rc_all.configurationMapName }}"
            items:
              - key: config.yml
                path: config.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
